feat: adding delete button in largest item section
elie222/inbox-zero pull request #119
Opened 2024-02-08 22:30 UTC by ketanMehtaa

fix #49 
Please review; it has not been completed yet.
not able to understand how to refetch after deletion

2024-02-08 22:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elie222/inbox-zero?pullRequest=119) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elie222/inbox-zero?pullRequest=119) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elie222/inbox-zero?pullRequest=119) it.</sub>

2024-02-08 22:39 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +import { ExternalLinkIcon, Trash2 } from "lucide-react";
Small change but rename to `Trash2Icon` to be consistent.

2024-02-08 22:40 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +  const { isLoading: buttonLoader, onLoad } = useStatLoader();
Stats loaded isn't needed here. You can delete this line.

2024-02-08 22:42 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +  }, []);
This doesn't do anything. Just call this direct:
`onTrashMessage(messageId)`

2024-02-08 22:42 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +                            onTrash(item.id ? item.id : "");
don't call onTrash when there's no id.

You can do:

```ts
if (item.id) onTrashMessage(item.id)
```

2024-02-08 22:43 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
>    const { data, isLoading, error } = useSWRImmutable<
Add `mutate` here to refetch after delete.
Then call it with `mutate()`:

```ts
if (item.id) {
  onTrashMessage(item.id);
  mutate();  
}
```

2024-02-08 22:44 UTC, elie222 commented
> fix #49 Please review; it has not been completed yet. not able to understand how to refetch after deletion

Here's how:

https://github.com/elie222/inbox-zero/pull/119/files#r1483674362

2024-02-09 17:48 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +                            : null}
Can use the spinner while deleting.

2024-02-09 17:49 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +                          disabled={item.id ? deletingStatus[item.id] : true}
`deletingStatus[item.id!]` is fine. These will always have an id. It's just annoying with the gmail api.

2024-02-09 17:51 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +                          {item.id
assume it has an id here too. With id!

2024-02-09 17:52 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +  const [deletingStatus, setDeletingStatus] = useState<Record<string, boolean>>(
You can change this to `isDeleting, setIsDeleting` and move it into the row level.

2024-02-09 17:52 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +  };
Can move this to the row level too. Just pass down mutate as a prop.

2024-02-09 17:53 UTC, elie222 commented
Thanks. Made some more comments!

2024-02-09 18:08 UTC, ketanMehtaa commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +                            : null}
sure

2024-02-09 18:23 UTC, ketanMehtaa commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +  const [deletingStatus, setDeletingStatus] = useState<Record<string, boolean>>(
const [isDeleting, setIsDeleting] = useState<Record<string, boolean>>({});
like this ?

2024-02-09 18:31 UTC, ketanMehtaa commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +  };
onClick={() => {
                            if (item.id) {
                              // onTrash(item.id);
                              setIsDeleting((prevMap: any) => ({
                                ...prevMap,
                                [item.id!]: true,
                              }));
                              onTrashMessage(item.id!);
                              mutate();
                            }
                          }}
                        > like this ?

2024-02-09 19:52 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +  const [deletingStatus, setDeletingStatus] = useState<Record<string, boolean>>(
Like this:

```tsx
const [isDeleting, setIsDeleting] = useState(false);
```

And then move it into the row (under `.map(() => {`)

2024-02-09 19:53 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +  const [deletingStatus, setDeletingStatus] = useState<Record<string, boolean>>(
You can have it all local to the row. Don't think there's any need to pass that state up to the parent component.

2024-02-09 20:37 UTC, ketanMehtaa commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +  const [deletingStatus, setDeletingStatus] = useState<Record<string, boolean>>(
![image](https://github.com/elie222/inbox-zero/assets/45426198/18478957-a164-4656-a9a7-50fa6a233cee)

2024-02-11 00:42 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +  const [deletingStatus, setDeletingStatus] = useState<Record<string, boolean>>(
Create a new component to do useState

2024-02-11 06:24 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +                  const [isDeleting, setIsDeleting] = useState(false);
Ya, this won't work. Needs to be its own component. But right idea.

2024-02-11 06:25 UTC, elie222 commented on apps/web/app/(app)/stats/LargestEmails.tsx
> +                              onTrashMessage(item.id!);
May want to await this, so that mutate happens after the delete is complete

2024-02-12 01:37 UTC, elie222 commented on apps/web/app/(app)/stats/DeleteLargestEmail.tsx
> +export function DeleteLargestEmail(props: {
This doesn't need to go into a new file

2024-02-12 01:37 UTC, elie222 commented on apps/web/app/(app)/stats/DeleteLargestEmail.tsx
> +  mutate: () => Promise<any>;
I think you can change `any` to `void`

2024-02-12 01:38 UTC, elie222 requested changes
Hey, mostly fine. Just move the new component into `apps/web/app/(app)/stats/LargestEmails.tsx`. It doesn't need a new file.

2024-02-12 18:26 UTC, ketanMehtaa commented on apps/web/app/(app)/stats/DeleteLargestEmail.tsx
> +  mutate: () => Promise<any>;
![image](https://github.com/elie222/inbox-zero/assets/45426198/605d3bb3-3d06-44d0-9451-82d590771da0)

not working with void , in codebase we are using  mutate with any only

2024-02-12 18:30 UTC, ketanMehtaa commented
> Hey, mostly fine. Just move the new component into `apps/web/app/(app)/stats/LargestEmails.tsx`. It doesn't need a new file.

Done.

2024-02-16 15:13 UTC, merged

2024-02-16 15:13 UTC, elie222 commented
> > Hey, mostly fine. Just move the new component into `apps/web/app/(app)/stats/LargestEmails.tsx`. It doesn't need a new file.
> 
> Done.

Nice! The final version looks pretty clean!