Add GROQ support
elie222/inbox-zero pull request #254
Opened 2024-11-01 17:06 UTC by 0xrushi

2024-11-01 17:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elie222/inbox-zero?pullRequest=254) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elie222/inbox-zero?pullRequest=254) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elie222/inbox-zero?pullRequest=254) it.</sub>

2024-11-03 00:54 UTC, elie222 commented on apps/web/utils/error.ts
> +  );
Did you actually check this worked or just added what you thought made sense?

The reason for these checks is just to help with Sentry error reporting (and then also report errors back to the user if we notice errors pop up).

But if it was just a guess at what the error messages are, then I think we can remove this code for now.

2024-11-03 00:55 UTC, elie222 requested changes
Just left one note about Groq errors

2024-11-03 01:33 UTC, 0xrushi commented on apps/web/utils/error.ts
> +  );
Not sure about the exact error messages, but groq does have rate limit and invalid api key error in docs.

2024-11-03 01:57 UTC, 0xrushi commented on apps/web/utils/error.ts
> +  );
Removed  ✅

2024-11-03 17:43 UTC, elie222 commented
@0xrushi could you also sign the license please. It's one of the pending checks

2025-01-09 10:45 UTC, elie222 commented
Added here:
https://github.com/elie222/inbox-zero/pull/298

Thanks!

2025-01-09 10:45 UTC, closed without merging