#issue:81 Mark emails as read
elie222/inbox-zero pull request #83
Opened 2024-01-07 11:27 UTC by Shalom2212

Created a mail read and unread function
added a button in ActionButtons where a user can Read or Unread a mail
![contribute:issue #81 (1)](https://github.com/elie222/inbox-zero/assets/91962940/4f1b04c2-8889-412f-a8b3-64418755dcc7)
![contribute:issue #81 (2)](https://github.com/elie222/inbox-zero/assets/91962940/0683a956-1fd6-4ff4-875f-4a25a841465f)

2024-01-07 11:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elie222/inbox-zero?pullRequest=83) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elie222/inbox-zero?pullRequest=83) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elie222/inbox-zero?pullRequest=83) it.</sub>

2024-01-07 18:28 UTC, elie222 requested changes
Thanks for the PR! Needs a bit of fixing.

Left a few comments about naming, misuse of React state and useMemo.

Also the most natural place to read in an email is when a row is clicked and a user has actually read the email.

2024-01-07 18:28 UTC, elie222 commented on apps/web/components/ActionButtons.tsx
> +  const [isReadUnreading, setisReadUnreading] = useState(false);
`setisReadUnreading` => `setIs`

2024-01-07 18:28 UTC, elie222 commented on apps/web/components/ActionButtons.tsx
> +  }, [isRead]);
Not sure what the goal is here but this isn't how `useMemo` is used.

Learn more here: https://react.dev/reference/react/useMemo

2024-01-07 18:28 UTC, elie222 commented on apps/web/components/ActionButtons.tsx
> +  const [isStateRead, setIsStateRead] = useState(isRead);
Don't think you want to use this local state at all. You want to know the state of the email from the row itself. We use it other places to mark the row color as read.

2024-01-07 18:28 UTC, elie222 commented on apps/web/utils/gmail/label.ts
> +}
I'd be okay with these two functions being one. But not critical.

2024-01-07 18:28 UTC, elie222 commented on apps/web/utils/gmail/label.ts
> +export async function markReadLabel(options: {
`readEmail` may be better

2024-01-07 18:28 UTC, elie222 commented on apps/web/utils/gmail/label.ts
> +export async function unMarkReadLabel(options: {
`markEmailUnread`

`unMark` is wrong as is

2024-01-07 18:28 UTC, elie222 commented on apps/web/utils/actions-client.ts
> +export async function onMarkUnmarkReadAction(
The naming is a bit all over the place here. `onMarkUnmarkReadAction`

It's either mark and unmark. But simpler might just be: `onMarkReadAction`

2024-01-07 18:28 UTC, elie222 commented on apps/web/utils/actions.ts
> +import { threadId } from "worker_threads";
Bad import

2024-01-07 18:28 UTC, elie222 commented on apps/web/components/email-list/EmailPanel.tsx
> +  }, [lastMessage?.labelIds]);
Don't think we need any extra state here. We were already marking rows as gray/white. See how that was done without state. We just get the row data passed in as props.

2024-01-07 18:28 UTC, elie222 commented on apps/web/components/ActionButtons.tsx
> +          },
Gmail uses the terminology "Mark as read" and "Mark as unread" - I'd use that so you don't have to reinvent the wheel here.

2024-01-07 18:28 UTC, elie222 commented on apps/web/components/ActionButtons.tsx
> +  const [isReadUnreading, setisReadUnreading] = useState(false);
`isReadUnreading` is bad in any case.

`markingRead`, and `setMarkingRead` is better. Or:
`isMarkingRead`, and `setIsMarkingRead` is better.

2024-01-08 17:07 UTC, Shalom2212 commented
> Thanks for the PR! Needs a bit of fixing.
> 
> Left a few comments about naming, misuse of React state and useMemo.
> 
> Also the most natural place to read in an email is when a row is clicked and a user has actually read the email.

Thank you For your comments, i'll fix it

2024-01-09 09:09 UTC, Shalom2212 commented
I made all the changes as you mentioned please review it, if any changes needed please comment it!!
Thank you

2024-01-12 08:17 UTC, closed without merging